### ISSUE TITLE
After syncing foe wweekend sem....the app shows holidays for every day and no course registered 

### ISSUE THREAD

**Issue by Talllwalker** [therealsujitk/android-vtop-chennai#92] opened 2023-08-11 00:56 UTC
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Environment**

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by Talllwalker** [comment] 2023-08-11 00:57
Pls fix this ASAP....it's very time consuming reading time table from vtop

**Comment by thebluedev** [comment] 2023-08-11 05:45
Can replicate, 
Simple registering for any course in the weekend sem completely wipes timetable for all other days.

**Comment by therealsujitk** [comment] 2023-08-11 05:47
Can one of you attach a screenshot of the weekend semester timetable page?

**Comment by thebluedev** [comment] 2023-08-11 06:08
It's not a seperate page, the just the empty slots in the normal time table gets filled, just clarifying

![Screenshot_20230811_111319](https://github.com/therealsujitk/android-vtop-chennai/assets/73629408/45576e85-cc15-48d8-bdba-cac42a46296a)

Above I've uploaded the screenshot.

**Comment by therealsujitk** [comment] 2023-08-11 06:58
@thebluedev What does the course list above this timetable look like?

**Comment by thebluedev** [comment] 2023-08-11 07:18
Exactly the same but with the weekend course and credits added to it

**Comment by therealsujitk** [comment] 2023-08-11 07:45
Is there anything about courses pending payment?

**Comment by thebluedev** [comment] 2023-08-11 11:33
Not that I know of, but there's a new generate invoice button, is that
possibly interfering?

**Comment by nexuswho** [comment] 2023-08-11 17:45
I had the same issue. Paying re-registration fees will remove generate invoice button and the issue will be gone

**Comment by thebluedev** [comment] 2023-08-11 18:21
Thanks for the clarification but I don't plan on doing that, I'm gonna take
the summer sem so having this not work for almost 2 weeks will be annoying
for many users

**Comment by therealsujitk** [comment] 2023-08-11 19:08
> Paying re-registration fees will remove generate invoice button and the issue will be gone

Yeah that's why I need to see the whole page so I can take care of this case as well as I've never seen it myself, if one of you can attach a screenshot whenever that would be great.

**Comment by thebluedev** [comment] 2023-08-12 14:12
![Untitled-1](https://github.com/therealsujitk/android-vtop-chennai/assets/73629408/eb5ccd41-3b94-4ea4-93e8-7089c73359f6)
Here you go, I've attached an image of the whole view

**Comment by therealsujitk** [comment] 2023-08-13 01:36
Thanks @thebluedev, I'll be closing this issue as it's a duplicate of #57. I'll try to fix this in the upcoming release.

**Closed by therealsujitk** 2023-08-13 01:36 UTC
Labels: bug, duplicate

**Comment by thebluedev** [comment] 2023-08-13 02:52
Ok, thanks for the update.

**Comment by therealsujitk** [comment] 2023-08-13 15:28
Are any of you by any chance in A block?
