### ISSUE TITLE
Multiple CAPTCHA and Not Able to Sync

### ISSUE THREAD

**Issue by mainak0907** [therealsujitk/android-vtop-chennai#121] opened 2024-04-07 13:38 UTC
## Bug Report

**Current Behavior**
When I am trying to Sync, it redirects to enter the CAPTCHA, but even after entering the correct CAPTCHA, it keeps on showing new CAPTCHA continuously for 10 - 15 times. And everytime after entering the CAPTCHA , it shows 'no value for semester' , without even prompting to enter or choose the semester.

**Steps to Reproduce**

1. Go to 'Profile'
2. Click on 'Sync Data'
3. Scroll down to 'CAPTCHA'

**Expected Behavior**

**Screenshots**

**Environment**

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by therealsujitk** [comment] 2024-04-07 13:45
Closing as duplicate of #119.

**Closed by therealsujitk** 2024-04-07 13:45 UTC
Labels: bug, duplicate
