### ISSUE TITLE
Opening courses crashes the app

### ISSUE THREAD

**Issue by VARUNKUMAR15** [therealsujitk/android-vtop-chennai#27] opened 2022-04-28 04:37 UTC
## Bug Report

In the course section when I access some courses the app crashes.

**Comment by therealsujitk** [comment] 2022-05-03 11:21
@VARUNKUMAR15 can you provide more information about this issue? A screenshot of your courses page from VTOP would be great.

**Comment by VARUNKUMAR15** [comment] 2022-05-08 17:57
This is the issue sometimes for some courses tooo

**Comment by therealsujitk** [comment] 2022-05-16 15:56
@VARUNKUMAR15 can you check if you still have this issue in **v4.0.1**.

**Comment by therealsujitk** [comment] 2022-06-08 16:52
Closing as a duplicate of #18.

**Closed by therealsujitk** 2022-06-08 16:52 UTC
Labels: bug, duplicate
