### ISSUE TITLE
App crash while clicking a subject in the Home Tab

### ISSUE THREAD

**Issue by hari0409** [therealsujitk/android-vtop-chennai#48] opened 2022-07-19 14:30 UTC
## Bug Report

**Current Behavior**
When i go to the home tab of the app & click on any time table unit to view the class room number & other data the app crashes.

**Steps to Reproduce**

1.Go to the Home Tab
2.Under any day choose any subject at any time
3.When clicked app crash

**Expected Behavior**
The data about that period must be visible like room number etc

**Screenshots**
![WhatsApp Image 2022-07-19 at 7 54 15 PM](https://user-images.githubusercontent.com/73524123/179775643-01f4912d-4a4f-4cc3-9b75-49d68df10251.jpeg)

**Environment**

- Android version:Android 10
- Device make & model:Mi A2

**Comment by therealsujitk** [comment] 2022-07-19 16:20
Closing as a duplicate of #45

**Closed by therealsujitk** 2022-07-19 16:20 UTC
Labels: bug, duplicate
