### ISSUE TITLE
Fall Semester 24-24 is not displaying when Sync.

### ISSUE THREAD

**Issue by Its-Suryakumar** [therealsujitk/android-vtop-chennai#137] opened 2024-12-25 03:32 UTC
## Bug Report

**Current Behavior**
When the sync is clicked for syncing Marks, all other semesters are displayed except for the Fall Semester 24-25 in the "Select Semester" menu.

**Environment**

- Android version: Android 13

**Comment by therealsujitk** [comment] 2024-12-25 04:13
Closing as duplicate of #133.

**Closed** 2024-12-25 04:13 UTC
Labels: bug, duplicate
