### ISSUE TITLE
Error 201. No value for semesters

### ISSUE THREAD

**Issue by thebluedev** [therealsujitk/android-vtop-chennai#112] opened 2024-03-24 03:34 UTC
## Bug Report

**Current Behavior**
Sync data failure. Error 201

**Steps to Reproduce**

1. Click on sync data button.
2. Complete captcha 
3. Error thrown

**Expected Behavior**
Data synced successfully

**Screenshots**
![Screenshot_20240324-085651](https://github.com/therealsujitk/android-vtop-chennai/assets/73629408/03991e58-b54d-4a68-987d-0e2f34dd6774)

**Comment by therealsujitk** [comment] 2024-03-24 04:54
Closing as duplicate of #109.

**Closed by therealsujitk** 2024-03-24 04:54 UTC
Labels: duplicate
