### ISSUE TITLE
201 no value for semesters error

### ISSUE THREAD

**Issue by GokulGirish0202** [therealsujitk/android-vtop-chennai#114] opened 2024-03-24 12:12 UTC
While trying to sync data, after captcha is entered, the error pops up stating 201 no value for semesters, after that the captcha reappears and the process is sent to an infinite loop

**Comment by therealsujitk** [comment] 2024-03-24 13:21
Closing as duplicate of #109.

**Closed by therealsujitk** 2024-03-24 13:21 UTC
Labels: duplicate
