### ISSUE TITLE
Not able to sync 

### ISSUE THREAD

**Issue by shivamkjha** [therealsujitk/android-vtop-chennai#111] opened 2024-03-22 10:24 UTC
## Bug Report

**Current Behavior**
When I'm trying to sync , its showing the same error, "No semesters found" It was resolved after the last update but it started again

**Steps to Reproduce**

1. Go to profile
2. Click on sync
3. Fill the capcha

**Screenshots**
![Screenshot_2024-03-22-15-55-00-219_tk.therealsuji.vtopchennai.jpg](https://github.com/therealsujitk/android-vtop-chennai/assets/88222939/651d5596-a968-43a6-967e-0440a4552c5a)

- Android version: 
- Device make & model: 

**Possible Solution**

**Additional Context**

**Comment by therealsujitk** [comment] 2024-03-22 15:36
Closing as duplicate of #109.

**Closed by therealsujitk** 2024-03-22 15:36 UTC
Labels: duplicate
