### ISSUE TITLE
Courses and timetable not being downloaded on data sync

### ISSUE THREAD

**Issue by YamiSukehiro24** [therealsujitk/android-vtop-chennai#68] opened 2022-12-11 19:30 UTC
App is not getting synced with vtop for the new winter semester .It is (empty)nil in courses and timetable as well.

**Comment by therealsujitk** [comment] 2022-12-12 05:46
@YamiSukehiro24 can you give me some more information? Your model and OS,  if any error show up? If the timetable page working on your VTOP portal? If you've tried signing out of the app and signing back in?

**Comment by YamiSukehiro24** [comment] 2022-12-12 06:00
> @YamiSukehiro24 can you give me some more information? Your model and OS, if any error show up? If the timetable page working on your VTOP portal? If you've tried signing out of the app and signing back in?
> 
> **Edit:** If you don't mind, it'll be great if you shared your entire timetable page here (courses + timetable)

@therealsujitk 
My phone model is OnePlus Nord ce 5g....it is a stock Android and oxygen OS hybrid.The time table is shown and is available in VTOP portal.
The problem is that the time table is not showing and I tried signing out and in multiple times and also reinstalled and tried as well.

Here are vtop app screenshots 
![Screenshot_2022-12-12-11-26-26-34_6573c7e73bb09b157d08de748cac469a](https://user-images.githubusercontent.com/91149481/206970921-cda79530-cbda-40a6-b90f-826b9ff5cc84.jpg)
![Screenshot_2022-12-12-11-26-16-67_6573c7e73bb09b157d08de748cac469a](https://user-images.githubusercontent.com/91149481/206970929-a7910ed8-3211-4a22-a4c3-3cee75c1c219.jpg)

Vtop website screen shot
![Screenshot_2022-12-12-11-30-21-34_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91149481/206971370-02acb2fc-3178-409e-8e9c-9988f0563060.jpg)
![Screenshot_2022-12-12-11-29-37-41_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/91149481/206971382-4d25b66a-1849-4082-8908-96257ea1e442.jpg)

**Comment by therealsujitk** [comment] 2022-12-12 06:10
@YamiSukehiro24 are your course registrations not confirmed yet, i.e. payment not complete? I'm guessing that's the cause of this issue. It'll resolve itself after the payment is complete. I'll release a fix for this case as well as soon as I get some free time. If you don't mind can you send me the whole course table (including the right part that's been cut)?

**Closed** 2022-12-12 06:12 UTC
Labels: bug, duplicate

**Comment by YamiSukehiro24** [comment] 2022-12-12 06:18
> 

@therealsujitk 
Got it and thanks

The right part.
![Screenshot_2022-12-12-11-45-50-49_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91149481/206974287-fe30f677-52fa-4c58-be15-0ea499c95e88.jpg)
