### ISSUE TITLE
No Option in Select Semester for Fall Semester 24-25

### ISSUE THREAD

**Issue by sheshank1212** [therealsujitk/android-vtop-chennai#136] opened 2024-12-23 03:55 UTC
![Screenshot_2024-12-23-09-23-33-89_6573c7e73bb09b157d08de748cac469a](https://github.com/user-attachments/assets/74ac1127-3cd9-48c6-8e77-a0f2363deed6)

**Comment by therealsujitk** [comment] 2024-12-24 03:10
Closing at duplicate of #133.

**Closed** 2024-12-24 03:10 UTC
Labels: bug, duplicate
